fastlane_version "2.28.3"
default_platform :ios

platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the certificate and profile are up to date"
  lane :beta do
    update_code_signing
    scan(
      clean: true,
      device: "iPhone SE"
    )
    build
    pilot(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    update_code_signing
    build
    deliver(force: true)
  end
end

def update_code_signing
  match(
      git_url: "https://github.com/minhpo/fastlane_match.git",
      type: "appstore"
    )
end

def build
  # Disable automatic signing as recommended https://docs.fastlane.tools/codesigning/getting-started/
  disable_automatic_code_signing(
    path: "ci.xcodeproj"
  )
  get_build_number
  increment_build_number
  gym
  enable_automatic_code_signing(
    path: "ci.xcodeproj"
  )
end